### PR TITLE
Fix spec

### PR DESCRIPTION
**Pull request by tsuwatch**
Now, Can we open current branch?
So, Fix to open current branch.
And I can't run spec in my environment, fix it.

### CODE REVIEW

**Comment by k0kubun** [comment]
Nice fix! Thank you :+1:

**Comment by tsuwatch** [comment]
Thank you! :satisfied:

**Comment by tsuwatch** [comment]
Sorry, I forgot to run `rake embed`. :cry:

**Comment by k0kubun** [comment]
Done 526322f5add9c141318cea3905d707c3f5d1a9f9 :ok_woman:

**Comment by tsuwatch** [comment]
:bow: :bow:

**Pull request merged**
